version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: pip install requests

      - run:
          name: Run HW02b tests
          command: python -m unittest test_triangle.py

      - run:
          name: Run HW03a tests
          command: |
            cd hw03a
            python -m unittest hw03a/test_github_api.py

workflows:
  build-and-test:
    jobs:
      - build